# Builds a Python package and publish it to PyPI when a new tag is
# created.

name: PyPI publishing

on:
  # Runs on creating a new tag starting with 'v', e.g. 'v1.0.3'
  push:
    tags: ['v*']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pypi-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # full history with tags to get the version number by versioningit

      - name: Set up pixi
        uses: ./.github/actions/setup-pixi

      - name: Create Python package
        run: pixi run default-build

      - name: Publish to PyPI
        uses: ./.github/actions/publish-to-pypi
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
